# GitHub Sponsors
# github: LuisGamas

# Buy Me A Coffee
buy_me_a_coffee: luisgamas

# PayPal (Usando custom para enlaces externos)
custom: ["https://www.paypal.com/donate/?hosted_button_id=NYCR5M6QHZ7JC"]
